{% set python_min = "3.10" %}
{% set name = "cc-plugin-cc6" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4df319528d2b7d424fd0961f68cce37d42e16b325e6a05f04ad31be6068450d7
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cftime
    - cf_xarray
    - compliance-checker >=5.1.2
    - netcdf4
    - pandas
    - xarray
    - pooch

test:
  imports:
    - cc_plugin_cc6
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/euro-cordex/cc-plugin-cc6
  summary: Compliance Checker CORDEX-CMIP6 plugin
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sol1105
    - larsbuntemeyer
